{% set name = "spacy-transformers" %}
{% set module_name = "spacy_transformers" %}
{% set version = "1.3.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3764ada8652a3984bd996fc301e4a7b4d8379228be50f7535070d5ee0d47beeb


build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - numpy
    - setuptools
    - wheel
    - cython >=0.25
  run:
    - python
    - spacy >=3.5.0,<4.0.0
    - transformers >=3.4.0,<4.37.0
    - pytorch >=1.8.0
    - srsly >=2.4.0,<3.0.0
    - spacy-alignments >=0.7.2,<1.0.0

test:
#  requires:
#    - pytest
  imports:
    - {{ module_name }}
#  commands:
#    - python -m pytest --tb=native --pyargs {{ module_name }}

about:
  home: https://spacy.io
  license: MIT
  license_file: LICENSE
  summary: Use pretrained transformers like BERT, XLNet and GPT-2 in spaCy
  description: |
    This package provides spaCy components and architectures to use transformer
    models via Hugging Face's transformers in spaCy. The result is convenient
    access to state-of-the-art transformer architectures, such as BERT, GPT-2,
    XLNet, etc.
  doc_url: https://github.com/explosion/spacy-transformers
  dev_url: https://github.com/explosion/spacy-transformers

extra:
  recipe-maintainers:
    - honnibal
    - ines
    - adrianeboyd
